version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "graphql"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  server:
    build: .
    environment:
      DATABASE: "host=postgres port=5432 user=user password=password dbname=graphql sslmode=disable"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  data:
